### ISSUE TITLE
[bug] ReferenceError: [BABEL] unknown: Unknown option

### ISSUE THREAD

**Issue by subdavis** [VIAME/VIAME-Web#142]
I'm pretty stuck right now with some errors from babel-jest on this branch: https://github.com/VIAME/VIAME-Web/tree/housekeeping/track-centric-fix-linting

```
  ● Test suite failed to run
    ReferenceError: [BABEL] unknown: Unknown option: /home/brandon/github.com/VIAME-Web/client/node_modules/@vue/cli-plugin-babel/preset.js.overrides. Check out http://babeljs.io/docs/usage/options/ for more information about options.
    A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:
    Invalid:
      `{ presets: [{option: value}] }`
    Valid:
      `{ presets: [['presetName', {option: value}]] }`
    For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options. (While processing preset: "/home/brandon/github.com/VIAME-Web/client/node_modules/@vue/cli-plugin-babel/preset.js")
      at Logger.error (node_modules/babel-core/lib/transformation/file/logger.js:41:11)
      at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
          at Array.map (<anonymous>)
      at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
      at OptionManager.mergePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
      at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
      at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
      at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
```

This isn't yet on master, but I'm logging the issue to document the solution.

**Comment by subdavis** [comment]
This was resolved.  I believe it involved using a different typescript config when running jest tests.
