### ISSUE TITLE
500 Error on detection load

### ISSUE THREAD

**Issue by subdavis** [VIAME/VIAME-Web#335]
```
girder_1         | INFO:172.27.0.1 - - [18/Sep/2020:16:23:49] "GET /api/v1/folder/5efe2bc119c003cf094ede80 HTTP/1.1" 200 543 "https://viame.kitware.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"
girder_1         | ERROR:500 Error
girder_1         | Traceback (most recent call last):
girder_1         |   File "/opt/venv/lib/python3.7/site-packages/girder/api/rest.py", line 629, in endpointDecorator
girder_1         |     val = fun(self, path, params)
girder_1         |   File "/opt/venv/lib/python3.7/site-packages/girder/api/rest.py", line 1190, in GET
girder_1         |     return self.handleRoute('GET', path, params)
girder_1         |   File "/opt/venv/lib/python3.7/site-packages/girder/api/rest.py", line 946, in handleRoute
girder_1         |     val = handler(**kwargs)
girder_1         |   File "/opt/venv/lib/python3.7/site-packages/girder/api/access.py", line 57, in wrapped
girder_1         |     return fun(*args, **kwargs)
girder_1         |   File "/opt/venv/lib/python3.7/site-packages/girder/api/describe.py", line 679, in wrapped
girder_1         |     return fun(*args, **kwargs)
girder_1         |   File "/opt/venv/lib/python3.7/site-packages/viame_server/viame_detection.py", line 255, in get_detection
girder_1         |     if "csv" in file["exts"]:
girder_1         | TypeError: 'NoneType' object is not subscriptable
girder_1         | Additional info:
girder_1         |   Request URL: GET http://viame.kitware.com/api/v1/viame_detection
girder_1         |   Query string: folderId=5efe2bc119c003cf094ede80&formatting=track_json
girder_1         |   Remote IP: 172.27.0.1
girder_1         |   Request UID: 13ecebf8-72cf-4686-b0aa-55b1c492b9f1
girder_1         | INFO:rest.request

```

**Comment by subdavis** [comment]
This doesn't make any sense

``` python
        detectionItems = list(
            Item().findWithPermissions(
                {"meta.detection": str(folder["_id"])}, user=self.getCurrentUser(),
            )
        )
        detectionItems.sort(key=lambda d: d["created"], reverse=True)
        if not len(detectionItems):
            return None
        file = Item().childFiles(detectionItems[0])[0]

        # TODO: deprecated, remove after we migrate to json
        if "csv" in file["exts"]:
            return viame.load_csv_as_tracks(file)
        return File().download(file, contentDisposition="inline")
```

somehow `len(detectionItems)` is true but `file` is None.    I've verified that `db.item.find({"meta.detection": "5efe2bc119c003cf094ede80"});` returns no results, so `len(detectionItems)` should be false.

**Comment by subdavis** [comment]
I messed up and I'm looking at the wrong code block.
